### PR TITLE
45 pgvector insert

### PR DESCRIPTION
**Pull request by choccccy**
from issue #45, and with @choccccy's addition of chatlog storage methods for `PGvectorHelper`, and having broken document databasing and chatlog databasing into their own subclasses of `PGvectorHelper`

see the [demo notebook](https://github.com/OoriData/OgbujiPT/blob/cecefca1e30ac4ca9ff7b0395947e41c82b8500c/demo/PGvector_demo.ipynb) for a better explaination of @choccccy's changes

### CODE REVIEW

**Comment by choccccy** [comment]
This PR is not really ready right now, but we need it soon so we're starting the process now.

**Review by uogbuji — APPROVED** [review]
Approving changes to date, though more will be required.

**Review by chimezie — APPROVED** [review]
Looks good

**Comment by uogbuji** [comment]
OK I've done another review pass with @choccccy, who is working on some subsequent changes. This is almost ready to land. @kaischuygon's work is another key bit.

**Pull request merged**
